'use strict';
const $=id=>document.getElementById(id);
const state={scenario:'pending',verified:false,report:null,view:'customer',referenceMatched:false};
const reasons={unrecognised:'I didn’t authorise this payment',deceived:'I was deceived into making this payment',recipient:'The recipient looks suspicious'};
const STORAGE_KEY='payment-protection-demo-records-v1';
function readRecords(){try{const value=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');return Array.isArray(value)?value.filter(item=>item&&item.paymentReference==='DEMO-TXN-08421').slice(-50):[];}catch{return [];}}
function writeRecords(records){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(records.slice(-50)));return true;}catch{return false;}}
function saveReferenceRecord(report){const records=readRecords();records.push({savedAt:report.createdAt,paymentReference:'DEMO-TXN-08421',caseReference:report.id,scenario:report.scenario,reason:report.reason,outcome:report.outcome});const saved=writeRecords(records);renderSavedRecords();return saved;}
function formatSavedTime(value){const date=new Date(value);return Number.isNaN(date.getTime())?'Unknown':date.toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'});}
function renderSavedRecords(){const records=readRecords();const body=$('records-body');body.replaceChildren();for(const record of records.slice().reverse()){const row=document.createElement('tr');for(const value of [formatSavedTime(record.savedAt),record.paymentReference,record.caseReference,record.outcome]){const cell=document.createElement('td');cell.textContent=value;row.appendChild(cell);}body.appendChild(row);}$('records-empty').classList.toggle('hidden',records.length>0);$('records-table-wrap').classList.toggle('hidden',records.length===0);$('download-records').disabled=records.length===0;$('clear-records').disabled=records.length===0;}
function csvCell(value){return `"${String(value??'').replaceAll('"','""')}"`;}
function downloadRecords(){const records=readRecords();if(!records.length)return;const rows=[['Saved at','Payment reference','Case reference','Scenario','Reason','Outcome'],...records.map(r=>[r.savedAt,r.paymentReference,r.caseReference,r.scenario,r.reason,r.outcome])];const csv=rows.map(row=>row.map(csvCell).join(',')).join('\r\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='payment-reference-log.csv';document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),0);$('storage-note').textContent=`Downloaded ${records.length} saved demo reference${records.length===1?'':'s'} as payment-reference-log.csv.`;}
function clearRecords(){if(!readRecords().length)return;if(!window.confirm('Clear all saved demo references from this browser?'))return;try{localStorage.removeItem(STORAGE_KEY);}catch{}renderSavedRecords();$('storage-note').textContent='The browser-local demo reference log has been cleared.';}
function showView(view){if(!['customer','investigation'].includes(view))throw Error('Unknown view');state.view=view; $('customer-view').classList.toggle('hidden',view!=='customer');$('investigation-view').classList.toggle('hidden',view!=='investigation');for(const v of ['customer','investigation']){$(v+'-tab').classList.toggle('active',view===v);$(v+'-tab').setAttribute('aria-pressed',String(view===v));}$('breadcrumb').textContent=view==='customer'?'PAYMENT REVIEW':'INVESTIGATION DESK';$('page-title').textContent=view==='customer'?'Find a payment. Take the next step.':'Every report. A clear evidence trail.';$('page-subtitle').textContent=view==='customer'?'Look up a sample payment by its reference, review the details and report a concern.':'Review the sample case, payment references and available signals.';}
function updateScenario(){const pending=state.scenario==='pending';$('payment-status').textContent=pending?'Pending review':'Completed';$('detail-status').textContent=pending?'Awaiting release':'Funds transferred';$('payment-notice').querySelector('p').textContent=pending?'This sample payment has not been released. A cancellation request would ask the bank to stop it before processing.':'This sample payment has already completed. Submit a fraud report and request a recall; recovery cannot be guaranteed.';$('submit-report').textContent=pending?'Submit report & request cancellation':'Submit report & request recall';$('request-explanation').textContent=pending?'The demo will simulate a cancellation for an eligible pending transfer and create a fraud case. A real stop requires confirmation from the bank.':'A completed transfer cannot simply be cancelled. The demo will record a recall request and open a fraud case; funds are not shown as recovered.';}
function openReport(){if(state.report||!state.referenceMatched)return;state.verified=false;$('review-step').classList.remove('hidden');$('verify-step').classList.add('hidden');$('step-1').classList.add('selected');$('step-2').classList.remove('selected');$('simulate').classList.remove('hidden');$('verified-message').classList.add('hidden');$('submit-report').disabled=true;updateScenario();$('report-dialog').showModal();}
function simulate(){state.verified=true;$('simulate').classList.add('hidden');$('verified-message').classList.remove('hidden');$('submit-report').disabled=false;$('submit-report').focus();}
function submitReport(){if(!state.verified||!state.referenceMatched||state.report) return;const pending=state.scenario==='pending';const now=new Date().toISOString();state.report={id:'DEMO-CASE-1048',reason:reasons[$('reason').value],createdAt:now,outcome:pending?'Cancelled in simulation':'Recall requested in simulation',scenario:state.scenario};const stored=saveReferenceRecord(state.report);$('report-dialog').close();$('payment-status').textContent=pending?'Demo: cancelled':'Recall requested';$('payment-status').className='pill teal';$('detail-status').textContent=pending?'Cancelled in simulation':'Completed · recall requested';$('payment-notice').querySelector('p').textContent=pending?'The simulated stop was successful. No money moved in this demo. The fraud case remains open for review.':'The simulated recall request is recorded. This does not mean the payment was reversed or that funds will be recovered.';$('report-button').disabled=true;$('report-button').textContent='Report submitted';$('scenario').disabled=true;$('receipt').innerHTML=`<h3>✓ ${pending?'Payment cancelled in this simulation':'Recall requested in this simulation'}</h3><p>Your sample fraud report is open. Case reference: <b>DEMO-CASE-1048</b>.</p><p class="small">${pending?'The simulated payment was eligible to be stopped. A live outcome depends on the payment status and bank confirmation.':'The payment remains completed. Recovery depends on the receiving institution and cannot be guaranteed.'}</p>${stored?'<p class="saved-badge">✓ Sample reference saved in this browser</p>':'<p class="small">Browser storage is unavailable, but you can still view this case during the current session.</p>'}<div class="receipt-actions"><button class="text-button" id="view-case">View investigation case →</button>${stored?'<button class="secondary" id="download-receipt">Download saved reference CSV</button>':''}</div>`;$('receipt').classList.remove('hidden');$('view-case').onclick=()=>showView('investigation');if(stored)$('download-receipt').onclick=downloadRecords;$('receipt').focus();renderCase();}
function renderCase(){const r=state.report;$('case-count').textContent=r?'1':'0';$('empty-case').classList.toggle('hidden',!!r);$('case-content').classList.toggle('hidden',!r);if(!r)return;const time=new Date(r.createdAt).toLocaleTimeString('en-GB',{timeZone:'UTC',hour:'2-digit',minute:'2-digit',second:'2-digit'})+' UTC';$('case-content').innerHTML=`<div class="case-header"><div><div class="eyebrow">FRAUD REVIEW · SAMPLE CASE</div><h2>${r.id}</h2><p>Northstar Trading Ltd · $2,450.00 · ${r.reason}</p></div><span class="pill amber">Investigation open</span></div><div class="case-grid"><article class="evidence-card"><h3>Payment & session evidence</h3><dl><div><dt>Payment reference</dt><dd class="mono">DEMO-TXN-08421</dd></div><div><dt>Source account</dt><dd>Everyday Checking •• 1094</dd></div><div><dt>Recipient reference</dt><dd>DEMO-REC-4821</dd></div><div><dt>Payment rail</dt><dd>Domestic transfer (sample)</dd></div><div><dt>Payment-session IP</dt><dd class="mono">192.0.2.24 (example address)</dd></div><div><dt>Approximate region</dt><dd>Denver, US (synthetic)</dd></div><div><dt>Payment device</dt><dd>Unrecognised browser (synthetic)</dd></div><div><dt>Reporting verification</dt><dd>Authenticated-session assumption (demo)</dd></div><div><dt>Payment outcome</dt><dd>${r.outcome}</dd></div></dl><p class="evidence-note">These are invented bank-record examples, not live tracking. IP-derived location can be affected by VPNs and network routing; it is a signal, not proof of identity or an attacker’s physical location.</p></article><article class="timeline"><h3>Case activity</h3><ol><li><b>Sample alert raised</b><p>New recipient and unfamiliar session flagged in the scenario.</p><small>Scenario event</small></li><li><b>Reporting intent confirmed</b><p>Intent confirmed in a simulated authenticated customer session.</p><small>${time} · This demo session</small></li><li><b>Customer report recorded</b><p>${r.reason}</p><small>${time} · This demo session</small></li><li><b>${r.outcome}</b><p>${r.scenario==='pending'?'Simulated stop confirmed before release.':'Recall request recorded. Recovery not confirmed.'}</p><small>${time} · Simulated bank response</small></li><li><b>Awaiting investigator review</b><p>Review bank-held records and coordinate with the receiving institution.</p><small>Next step · No real case has been sent</small></li></ol></article></div>`;}
function reset(){if($('report-dialog').open)$('report-dialog').close();state.scenario='pending';state.verified=false;state.report=null;clearLookup();$('scenario').value='pending';$('scenario').disabled=false;$('reason').value='unrecognised';$('report-button').disabled=false;$('report-button').innerHTML='I don’t recognise this payment <span>→</span>';$('payment-status').className='pill amber';$('receipt').classList.add('hidden');$('receipt').innerHTML='';updateScenario();renderCase();showView('customer');}
$('customer-tab').onclick=()=>showView('customer');$('investigation-tab').onclick=()=>showView('investigation');$('back-to-review').onclick=()=>showView('customer');$('report-button').onclick=openReport;$('close-dialog').onclick=()=>$('report-dialog').close();$('reset').onclick=reset;$('scenario').onchange=e=>{state.scenario=e.target.value;updateScenario();};$('continue').onclick=()=>{$('review-step').classList.add('hidden');$('verify-step').classList.remove('hidden');$('step-1').classList.remove('selected');$('step-2').classList.add('selected');$('simulate').focus();};$('back-step').onclick=()=>{$('verify-step').classList.add('hidden');$('review-step').classList.remove('hidden');$('step-1').classList.add('selected');$('step-2').classList.remove('selected');$('reason').focus();};$('simulate').onclick=simulate;$('submit-report').onclick=submitReport;
updateScenario();
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'get_demo_payment_state',description:'Read the sample payment scenario and simulated fraud case. No real banking data.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw Error('Expected an empty object');return{scenario:state.scenario,view:state.view,referenceMatched:state.referenceMatched,report:state.report};}},{signal:lifecycle.signal})).catch(()=>{});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}catch{}}

function clearLookup(){state.referenceMatched=false;$('payment-reference').value='';$('payment-reference').disabled=false;$('use-sample').disabled=false;$('reference-error').classList.add('hidden');$('reference-success').classList.add('hidden');$('payment-reference').removeAttribute('aria-invalid');$('payment-results').classList.add('hidden');$('lookup-empty').classList.remove('hidden');}
function findPayment(event){event?.preventDefault();const ref=$('payment-reference').value.trim().toUpperCase();$('reference-error').classList.add('hidden');$('reference-success').classList.add('hidden');if(ref!=='DEMO-TXN-08421'){state.referenceMatched=false;$('payment-results').classList.add('hidden');$('lookup-empty').classList.remove('hidden');$('reference-error').textContent=ref?'No demo payment matches that reference. Use DEMO-TXN-08421; real references and security codes are not accepted.':'Enter the sample payment reference to continue.';$('reference-error').classList.remove('hidden');$('payment-reference').setAttribute('aria-invalid','true');$('payment-reference').focus();return false;}
state.referenceMatched=true;$('payment-reference').value='DEMO-TXN-08421';$('payment-reference').removeAttribute('aria-invalid');$('reference-success').classList.remove('hidden');$('payment-results').classList.remove('hidden');$('lookup-empty').classList.add('hidden');return true;}
$('reference-form').onsubmit=findPayment;$('use-sample').onclick=()=>{$('payment-reference').value='DEMO-TXN-08421';findPayment();};
$('payment-reference').oninput=()=>{state.referenceMatched=false;$('reference-success').classList.add('hidden');$('reference-error').classList.add('hidden');$('payment-reference').removeAttribute('aria-invalid');$('payment-results').classList.add('hidden');$('lookup-empty').classList.remove('hidden');};
$('download-records').onclick=downloadRecords;$('clear-records').onclick=clearRecords;renderSavedRecords();
